### ISSUE TITLE
Script stops working after a few turns, an if run at the end of a battle, errors.

### ISSUE THREAD

**Issue by MaxAkito** [29988122/Fate-Grand-Order_Lua#208]
Hello, whenever I run the script it stops working after a few turns. 2-3 I couldn't tell. It also seems to stop when autoskill goes to a new stage. I am trying to farm the summer racing event.

Android version: 8.0.0
Phone Model: Samsung Galaxy S9
FGO Region: NA
Script Version: Latest as of this date
Connection method: Daemon (From PC)

The setup/config I use is the base config, and this custom one I made real quick that will be attached. (.txt so it can be uploaded)

I would appreciate any help, thank you. :)
[FGO_EN_REGULAR_SUMMER2019.txt](https://github.com/29988122/Fate-Grand-Order_Lua/files/3486823/FGO_EN_REGULAR_SUMMER2019.txt)

**Comment by MaxAkito** [comment]
![Lz0zvfp](https://user-images.githubusercontent.com/10167995/62789552-27149880-ba97-11e9-9910-c2227b0b9988.png)

After further investigation, I can make it about 4~ turns before it turns off, though on some maps it just stops working after switching to a different round (2/3 etc.). I also get this error if I reactivate it before the battle finishes/it's active when it finishes. Attached it to see if it (hopefully) helps.

**Comment by aurex77** [comment]
Hello, i didn't try on the summer event but i get the same error ar the end of each fight in the daily quest.

I fixed this by editing the file regular.lua at line 127 :
`if game.CONTINUE_REGION:exists(GeneralImagePath .. "confirm.png") then`

By this :
`if GameRegion == 'JP' and game.CONTINUE_REGION:exists(GeneralImagePath .. "confirm.png") then`

**Comment by MaxAkito** [comment]
Are you JP or EN? If JP do I need to change the 'JP' part to EN instead?

**Comment by aurex77** [comment]
I play on both.
But no change needed, just let `GameRegion == 'JP'` because this condition is for a new update only on JP which caused this error on the other versions.

**Comment by MaxAkito** [comment]
Just tried that, it removed the error thanks, I still have the problem of the script only working for a few turns though.

**Comment by aurex77** [comment]
Do you have another error when your script stop ?

**Comment by MaxAkito** [comment]
Nope, not at all. I can record a video if that helps.

**Comment by aurex77** [comment]
Yes, maybe it could help

**Comment by TryBane** [comment]
This is a result of a change I made to help with the new JP feature. Give me a few moments to fix this.

**Comment by TryBane** [comment]
I have applied a change that should solve the issue. I'm going to check it on my own, but it would be helpful if anyone else was looking to give it a test to ensure it works.

**Comment by TryBane** [comment]
Okay, after reviewing the dialogue in this thread, I realize that my change only fixes the crash at the battle finish portion. I will investigate the possible issues occurring in your game for now.

**Comment by MaxAkito** [comment]
I keep trying to record it, but it's difficult since Ankulua becomes the focus and it causes the video to mess up. Thank you for fixing the crash issue, and I hope you figure out why the script could possibly stop working randomly.

**Comment by TryBane** [comment]
The person I had testing the crash just told me the crash is still happening. Is that the case for you as well? @MaxAkito Or did you use the other guys' temporary fix?

**Comment by MaxAkito** [comment]
I used the other guys temp fix, I can test the one you uploaded if you want.

**Comment by TryBane** [comment]
Nah, I implemented his temp fix. It works for now so it isn't a big deal. Until the other servers begin getting the same change anyways.

**Comment by ArianTerra** [comment]
I have the same issue.
Support selection works fine, after entering the battle nothing happens at all.
If launching from battle the script stucks after 3-4 turns. With auto skill it works only until next battle stage.
Phone: Xiaomi Mi A2 Lite (screen with notch), Android 9, Media projection, Ankulua 8.3 pro, NA version
